# ruff.toml — standalone config (géén [tool.ruff] secties gebruiken)

line-length = 100
target-version = "py311"

# Helemaal overslaan (zijn demo's; stijl strikt linten is hier niet nodig)
extend-exclude = ["examples"]

[lint]
# Beperk je tot errors/pyflakes; laat W* voorlopig weg (zoals W291)
select = ["E", "F"]
ignore = []

[lint.per-file-ignores]
# Tests: sta samengestelde regels en ongebruikte imports toe
"tests/*" = ["E701", "E702", "F401"]

# Bestaande modules met inline statements/semicolons:
"src/a003558/cosmos.py" = ["E701", "E702"]
"src/a003558/viz_octa.py" = ["E701", "E702"]

# Typing-imports nog niet overal gebruikt:
"src/a003558/number_theory.py" = ["F401"]
