name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        extras: ["core", "viz"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install (core or viz)
        run: |
          python -m pip install --upgrade pip
          if [ "${{ matrix.extras }}" = "viz" ]; then
            python -m pip install -e ".[dev,viz]"
          else
            python -m pip install -e ".[dev]"
          fi

      - name: Lint (ruff)
        run: |
          ruff --version || python -m pip install ruff
          ruff check .

      - name: Run tests
        run: |
          python -m pip install pytest
          if [ "${{ matrix.extras }}" = "viz" ]; then
            pytest -q
          else
            # in core-variant geen matplotlib: viz-tests overslaan
            pytest -q -k "not viz"
          fi

      - name: Smoke import
        run: |
          python - << 'PY'
          import importlib, sys
          importlib.import_module("a003558")
          print("OK: import a003558")
          if "${{ matrix.extras }}" == "viz":
              importlib.import_module("a003558.viz")
              print("OK: import a003558.viz")
          PY
