name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies (editable + dev extras)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      # Optioneel: ruff lint (verwijder deze stap als je ruff niet gebruikt)
      - name: Lint with ruff
        run: |
          python -m pip install ruff
          ruff check .

      - name: Run tests
        run: |
          python -m pip install pytest
          pytest -q

      # Optioneel: coverage artefact
      - name: Upload coverage (if present)
        if: always() && hashFiles('coverage.xml') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
